language: objective-c
brefore_install:
     - brew update
     - brew install xctool
script: xctool -project Example/DAWeatherClient-Example.xcodeproj -scheme DAWeatherClient-Example -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=NO TEST_AFTER_BUILD=YES clean build
